backend:
  name: git-gateway
  branch: master
media_folder: static/assets
public_folder: /assets
publish_mode: editorial_workflow
collections:
  - name: blog
    label: Blog
    folder: /src/content/blog
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    editor:
      preview: false
    fields:
      - { name: type, label: Type, widget: hidden, default: blog }
      - { name: title, label: Title, widget: string }
      - { name: date, label: Date, widget: datetime }
      - { name: image, label: 'Featured Image', widget: image }
      - { name: body, label: Body, widget: markdown }
