backend:
  name: git-gateway
local_backend: true
media_folder: static/assets
public_folder: /assets
publish_mode: editorial_workflow
collections:
  - name: blog
    label: Blog
    folder: src/content/blog
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    editor:
      preview: false
    fields:
      - { name: type, label: Type, widget: hidden, default: blog }
      - { name: title, label: Title, widget: string }
      - { name: date, label: Date, widget: datetime }
      - { name: image, label: 'Featured Image', widget: image }
      - { name: body, label: Body, widget: markdown }
  - name: pages
    label: Pages
    editor:
      preview: false
    files:
      - name: index
        label: 'Landing Page'
        file: src/content/pages/index.md
        fields:
          - { name: type, label: Type, widget: hidden, default: page }
          - { name: path, label: Path, widget: hidden, default: index }
          - {
              name: mainMessage,
              label: 'Main Message',
              widget: string,
              pattern: ['.{12,50}', '12-50 characters allowed.'],
            }
          - {
              name: subMessage,
              label: 'Sub Message',
              widget: string,
              pattern: ['.{12,100}', '12-100 characters allowed.'],
            }
      - name: training
        label: 'Training Page'
        file: src/content/pages/training.md
        fields:
          - { name: type, label: Type, widget: hidden }
          - { name: path, label: Path, widget: hidden }
          - {
              name: mainMessage,
              label: 'Main Message',
              widget: string,
              pattern: ['.{12,50}', '12-50 characters allowed.'],
            }
          - {
              name: subMessage,
              label: 'Sub Message',
              widget: string,
              pattern: ['.{12,100}', '12-100 characters allowed.'],
            }
